Request some params to be entered.

diff --git a/extras/marauroad b/extras/marauroad
--- a/extras/marauroad
+++ b/extras/marauroad
@@ -1,4 +1,10 @@
 #!/bin/bash
 
-set LOCALCLASSPATH=/opt/marauroa/libs/jython.jar:/opt/marauroa/libs/mysql-connector.jar:/opt/marauroa/libs/log4j.jar
-java -cp "$LOCALCLASSPATH" -jar /opt/marauroa/libs/marauroa-1.92.jar -c server.ini -l
+if [ $# -eq 0 ]; then
+  echo "Missing params."
+  echo "Usage: $0 <game-server-plugin> <server.ini>
+  exit 1
+fi
+
+set LOCALCLASSPATH=$1:/opt/marauroa/libs/jython.jar:/opt/marauroa/libs/mysql-connector.jar:/opt/marauroa/libs/log4j.jar
+java -cp "$LOCALCLASSPATH" -jar /opt/marauroa/libs/marauroa-1.92.jar -c $2 -l
